@startuml

actor User
User -> AnnivListVC : UIを使ったユーザーアクション
AnnivListVC -> AnnivListPresenter : Presenterを生成（Viewの参照を渡す）
AnnivListPresenter -> AnnivListModel : Modelを生成する
entity Anniv
AnnivListModel -> Anniv : 記念日データを監視して取得
Anniv -> AnnivListModel : 記念日データのへ香があれば取得
AnnivListModel -> AnnivListPresenter : データや結果をPresenterに返す
AnnivListPresenter -> AnnivListVC : UIの変更を指示する
AnnivListVC -> User : Viewを更新してユーザーに表示する

@enduml
